"""Server-rendered HTML pages."""

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.templating import Jinja2Templates

from app.config import JINJA_TEMPLATES_DIR, REPO_ROOT
from app.services import trips as trips_svc

router = APIRouter()
templates = Jinja2Templates(directory=str(JINJA_TEMPLATES_DIR))


@router.get("/", response_class=HTMLResponse)
def index(request: Request):
    all_trips = trips_svc.scan_trips()
    upcoming, past, broken = trips_svc.split_trips(all_trips)
    return templates.TemplateResponse(
        request,
        "index.html",
        {
            "upcoming": [trips_svc.trip_card_meta(t) for t in upcoming],
            "past": [trips_svc.trip_card_meta(t) for t in past],
            "broken": broken,
            "park_options": trips_svc.load_park_options(),
            "nav": {"home_href": "/", "show_user_pill": True},
        },
    )


# Map-data overlay (jeffs_osm_overlay.html) lives at repo root because it's
# generated by scripts/overlay_osm_jeffs.py outside the trip dirs. Serve it +
# its raster JPG sibling so the trip page can deep-link to it. Trailing slash
# matters: the overlay HTML references its raster mosaic with a relative URL
# (`jeffs_osm_overlay_raster.jpg`), and that only resolves to
# `/overlay/jeffs_osm_overlay_raster.jpg` if the page itself was served at
# `/overlay/`.
@router.get("/overlay", include_in_schema=False)
def overlay_redirect():
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/overlay/", status_code=307)


@router.get("/overlay/")
def overlay_html():
    path = REPO_ROOT / "jeffs_osm_overlay.html"
    if not path.exists():
        # Suggest an actual trip directory (most-recently-modified) so the
        # hint is a runnable command, not a `<slug>` shell-redirect bomb.
        trips_dir = REPO_ROOT / "trips"
        suggestion = ""
        if trips_dir.is_dir():
            candidates = [p for p in trips_dir.iterdir() if p.is_dir()]
            if candidates:
                latest = max(candidates, key=lambda p: p.stat().st_mtime)
                suggestion = (
                    f" Try: python3 scripts/overlay_osm_jeffs.py "
                    f"--trip trips/{latest.name}/"
                )
        raise HTTPException(
            status_code=404,
            detail="Overlay not generated yet." + suggestion,
        )
    return FileResponse(path, media_type="text/html")


@router.get("/overlay/{filename}")
def overlay_asset(filename: str):
    # Sibling assets (raster mosaic JPG) live next to the overlay HTML. Lock
    # this down to the raster file specifically — no traversal.
    if filename != "jeffs_osm_overlay_raster.jpg":
        raise HTTPException(status_code=404)
    path = REPO_ROOT / filename
    if not path.exists():
        raise HTTPException(status_code=404)
    return FileResponse(path)
