"""Server-rendered HTML pages."""

from datetime import date as _date
from typing import Optional

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.templating import Jinja2Templates

from app.config import JINJA_TEMPLATES_DIR, REPO_ROOT
from app.services import trips as trips_svc

router = APIRouter()
templates = Jinja2Templates(directory=str(JINJA_TEMPLATES_DIR))


def _shape_for_card(entry: dict) -> dict:
    """Transform list_trips_v2 entry into card template shape."""
    return {
        "name": entry["slug"],
        "park_name": entry["park_name"] or entry["park"],
        "start_date": str(entry["start"]),
        "end_date": str(entry["end"]),
        "participant_count": entry["participant_count"],
        "days_label": "",
    }


@router.get("/", response_class=HTMLResponse)
def index(request: Request):
    today = _date.today()
    entries = trips_svc.list_trips_v2()
    upcoming = [_shape_for_card(e) for e in entries if e["start"] >= today]
    past = [_shape_for_card(e) for e in entries if e["start"] < today]
    return templates.TemplateResponse(
        request,
        "index.html",
        {
            "upcoming": upcoming,
            "past": past,
            "broken": [],
            "park_options": trips_svc.load_park_options(),
            "nav": {"home_href": "/", "show_user_pill": True},
        },
    )


# Map-data overlay (jeffs_osm_overlay.html) lives at repo root because it's
# generated by scripts/overlay_osm_jeffs.py outside the trip dirs. Serve it +
# its raster JPG sibling so the trip page can deep-link to it. Trailing slash
# matters: the overlay HTML references its raster mosaic with a relative URL
# (`jeffs_osm_overlay_raster.jpg`), and that only resolves to
# `/overlay/jeffs_osm_overlay_raster.jpg` if the page itself was served at
# `/overlay/`.
@router.get("/overlay", include_in_schema=False)
def overlay_redirect():
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/overlay/", status_code=307)


@router.get("/overlay/", response_class=HTMLResponse)
def overlay_html(request: Request, trip: Optional[str] = None):
    nav_ctx = {"home_href": "/", "show_user_pill": True}
    trip_label = None
    if trip:
        try:
            from app.services import trip_store
            t = trip_store.load(trips_svc.TRIPS_DIR / trip)
            trip_label = t.name
            nav_ctx["back_href"] = f"/trip/{trip}"
            nav_ctx["back_label"] = f"Back to {t.name}"
        except Exception:
            pass
    return templates.TemplateResponse(request, "overlay.html", {
        "nav": nav_ctx,
        "trip_label": trip_label,
    })


@router.get("/overlay/{filename}")
def overlay_asset(filename: str):
    # Sibling assets (raster mosaic JPG) live next to the overlay HTML. Lock
    # this down to the raster file specifically — no traversal.
    if filename != "jeffs_osm_overlay_raster.jpg":
        raise HTTPException(status_code=404)
    path = REPO_ROOT / filename
    if not path.exists():
        raise HTTPException(status_code=404)
    return FileResponse(path)
